language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.6
  - 0.8

script:
  - echo script
  
after_script:
  - echo after_script
  
deploy:
  provider: script
  skip_cleanup: true
  script: echo deploy
  on:
    branch: master

after_deploy:
  - echo after_deploy
